---
name: Download latest release artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Download latest appcast.xml
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          file: 'README.md'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print downloaded Artifact
        run: cat README.md
