---
name: Make Technical Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
#          fetch-depth: 0

          # When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN,
          # except workflow_dispatch and repository_dispatch, will not create a new workflow run. This
          # prevents you from accidentally creating recursive workflow runs.
          # https://stackoverflow.com/a/75348554/13213024
          token: ${{ secrets.PERSONAL_TOKEN }}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Determine next Hotfix Version
        id: next_tag
        env:
          GIT_TAG_INPUT: ${{ steps.get-latest-tag.outputs.tag }}
        run: |
          APP_VERSION=$(echo "$GIT_TAG_INPUT" | perl -lane 'while (/(v[0-9]+\.[0-9]+\.[0-9]+)(-([0-9]+))?/g) {print $1}')
          TECHNICAL_RELEASE=$(echo "$GIT_TAG_INPUT" | perl -lane 'while (/(v[0-9]+\.[0-9]+\.[0-9]+)(-([0-9]+))?/g) {print $3}')
          
          echo "App version: ${APP_VERSION}"
          echo "Technical Release: ${TECHNICAL_RELEASE}"
          
          NEXT_VERSION="${APP_VERSION}-$(($TECHNICAL_RELEASE+1))"
          echo "Next Release Tag: ${NEXT_VERSION}"
          
          echo "nextVersion=${NEXT_VERSION}" >> ${GITHUB_ENV}

      # Set Settings > Actions > General > "Workflow permissions" to "Read and write permissions"
      - name: Create Next Github Tag
        uses: EndBug/latest-tag@v1.6.1
        with:
          ref: ${{ env.nextVersion }}
