---
name: Make Hotfix Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

          # When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with
          # the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This
          # prevents you from accidentally creating recursive workflow runs.
          # https://stackoverflow.com/a/75348554/13213024
          token: ${{ secrets.PERSONAL_TOKEN }}
      #      - name: Get Previous tag
      #        id: previous_tag
      #        uses: WyriHaximus/github-action-get-previous-tag@v1
      #        env:
      #          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #        with:
      #          fallback: v0.0.0
      #          prefix: v
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Determine next Hotfix Version
        id: next_tag
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.get-latest-tag.outputs.tag }}

      # Set Settings > Actions > General > "Workflow permissions" to "Read and write permissions"
      - name: Create Next Hotfix Tag
        uses: EndBug/latest-tag@v1.6.1
        with:
          ref: ${{ steps.next_tag.outputs.v_patch }}
