---
name: Make Feature Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

          # When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN,
          # except workflow_dispatch and repository_dispatch, will not create a new workflow run. This
          # prevents you from accidentally creating recursive workflow runs.
          # https://stackoverflow.com/a/75348554/13213024
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Get Latest Release
        id: latest_release
        uses: joutvhu/get-release@v1
        with:
          latest: true
          prerelease: false
          pattern: '^v.*'
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse App Version
        env:
          GIT_TAG_INPUT: ${{ steps.latest_release.outputs.tag_name }}
        run: |
          APP_VERSION=$(echo "$GIT_TAG_INPUT" | perl -lane 'while (/(v[0-9]+\.[0-9]+\.[0-9]+)(-[0-9]+)?/g) {print $1}')
          echo "appVersion=${APP_VERSION}" >> ${GITHUB_ENV}

      - name: Determine Next Version
        id: next_tag
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ env.appVersion }}

      # Set Settings > Actions > General > "Workflow permissions" to "Read and write permissions"
      - name: Create Next Github Tag
        uses: EndBug/latest-tag@v1.6.1
        with:
          ref: ${{ steps.next_tag.outputs.v_minor }}
