---
name: Make Prerelease automatically

on:
  push:
    branches: [ main ]
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup versions
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "GITHUB_RUN_ID = ${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER = ${GITHUB_RUN_NUMBER}"

          GIT_TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          
          echo "GIT_TAG_VERSION=${GIT_TAG_VERSION}" >> ${GITHUB_ENV}
          echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}

      - name: Create Github Prerelease
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ env.GIT_TAG_VERSION }} (build: ${{ env.GITHUB_RUN_NUMBER }})"
          prerelease: true
          files: |
            LICENSE
            README.md
